config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root to: 'events#index'
  get '/eventos/sugerir(/:sent)', to: 'events#new', as: 'new_event'
  post '/eventos/sugerir', to: 'events#create', as: 'create_event'
  get '/eventos/:id', to: 'events#show', as: 'event'

  get '/contato(/:sent)', to: 'contacts#new', as: 'contact'
  post '/contato', to: 'contacts#create', as: 'create_contact'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  enum status: [ :pending, :active ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end

  def create
    Contacts::EmailService.send(contact_params)
    redirect_to contact_path(sent: 'enviado')
  end

  private
  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Events::DisplayService.all
  end

  def show
    @event = Events::DisplayService.show(params[:id])
  end

  def new
  end

  def create
    Events::CreateService.send(event_params)
    redirect_to new_event_path(sent: 'enviado')
  end

  private
  def event_params
    params.require(:event).permit(:title, :event_date, :more_info, :price, :description, :city, :state, :address)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<section class="hero is-danger is-bold">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Contato
      </h1>
    </div>
  </div>
</section>

<div class="container">

  <section class="hero">
    <div class="hero-body">
      <div class="container">
        <h2 class="subtitle">
        Sugestões, dúvidas e críticas são bem-vindas
        </h2>
      </div>
    </div>
  </section>

  <% if params[:sent] %>
    <div class="notification is-success">
      Seu contato foi enviado com sucesso!
    </div>
  <% end %>

  <%= form_tag(create_contact_path, method: :post) do %>

    <label for="name" class="label">Nome</label>
    <p class="control">
      <input required type="text" name="contact[name]" id="name" class="input">
    </p>

    <label for="email" class="label">E-mail</label>
    <p class="control">
      <input required type="email" name="contact[email]" id="email" class="input">
    </p>

    <label for="message" class="label">Mensagem</label>
    <p class="control">
      <textarea id="message" name="contact[message]" class="textarea"></textarea>
    </p>

    <div class="control is-grouped">
      <p class="control">
        <button type="submit" class="button is-danger">Enviar</button>
      </p>
    </div>

  <% end %>

</div> <!-- .container -->

app/views/events/index.html.erb
<section class="hero is-danger is-bold">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Eventos em Destaque
      </h1>
      <h2 class="subtitle">
        Veja quais são os próximos eventos de tecnologia no Brasil
      </h2>
    </div>
  </div>
</section>

<div class="container container--main">

  <div class="columns is-multiline">

    <% @events.each do |event| %>
    <div class="column is-4">

      <div class="card">
        <div class="card-content">
          <div class="media">
            <div class="media-content">
              <p class="title is-4 is-danger-text"><%= event.title %></p>
              <p class="subtitle is-6"><%= event.city %>, <%= event.state %></p>
            </div>
          </div>

          <div class="content">
            <p><%= event.description %></p>

            <p><i class="material-icons">place</i> <%= event.address %></p>
            <p><i class="material-icons">date_range</i> <%= I18n.l(event.event_date, format: '%d/%m/%Y') %></p>
            
            <a href="<%= event_path(event) %>" class="button is-danger">Ver Mais</a>
          </div> <!-- .content -->
        </div>
      </div> <!-- .card -->
      
    </div>
    <% end %>

  </div>

</div>

app/views/events/new.html.erb
<section class="hero is-danger is-bold">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        Sugerir Evento
      </h1>
    </div>
  </div>
</section>

<div class="container">

  <section class="hero">
    <div class="hero-body">
      <div class="container">
        <h2 class="subtitle">
        Sabe de algum evento que não está presente no site? Envie ele aqui!
        </h2>
        <h3 class="subtitle">
        Obs: Sujeito a aprovação.
        </h3>
      </div>
    </div>
  </section>

  <% if params[:sent] %>
    <div class="notification is-success">
      Seu evento foi enviado com sucesso!
    </div>
  <% end %>

  <%= form_tag(create_event_path, method: :post) do %>

    <label for="title" class="label">Nome</label>
    <p class="control">
      <input required type="text" name="event[title]" id="title" class="input">
    </p>

    <label for="description" class="label">Descrição</label>
    <p class="control">
      <textarea id="description" name="event[description]" class="textarea"></textarea>
    </p>

    <label for="city" class="label">Cidade</label>
    <p class="control">
      <input required type="text" name="event[city]" id="city" class="input">
    </p>

    <label for="state" class="label">Estado</label>
    <p class="control">
      <input required type="text" name="event[state]" id="state" class="input">
    </p>

    <label for="address" class="label">Endereço</label>
    <p class="control">
      <input required type="text" name="event[address]" id="address" class="input">
    </p>

    <label for="event_date" class="label">Data</label>
    <p class="control">
      <input required type="date" name="event[event_date]" id="event_date" class="input">
    </p>

    <label for="price" class="label">Valores</label>
    <p class="control">
      <input required type="text" name="event[price]" id="price" class="input">
    </p>

    <label for="more_info" class="label">Mais informações</label>
    <p class="control">
      <textarea id="more_info" name="event[more_info]" class="textarea"></textarea>
    </p>

    <div class="control is-grouped">
      <p class="control">
        <button type="submit" class="button is-danger">Enviar</button>
      </p>
    </div>

  <% end %>

</div> <!-- .container -->

app/views/events/show.html.erb
<section class="hero is-danger is-medium is-bold">
  <div class="hero-body">
    <div class="container">
      <h1 class="title">
        <%= @event.title %>
      </h1>
      <h2 class="subtitle">
        <i class="material-icons">place</i> <%= @event.city %>, <%= @event.state %>
      </h2>
    </div>
  </div>
</section>

<div class="container container--main">

  <div class="content">

    <div class="columns">
      <div class="column">

        <span class="tag is-large is-danger"><i class="material-icons">place</i> <%= @event.address %></span>
        <span class="tag is-large is-danger"><i class="material-icons">date_range</i> <%= I18n.l(@event.event_date, format: '%d/%m/%Y') %></span>
      
      </div>
    </div>

    <div class="columns">
      <div class="column">

        <div class="notification">
          <h2 class="title">Descrição</h2>
          <p><%= @event.description %></p>
        </div>

        <div class="notification">
          <h2 class="title">Valores</h2>
          <p><%= @event.price %></p>
        </div>

        <div class="notification">
          <h2 class="title">Mais Informações</h2>
          <p><%= auto_link(@event.more_info) %></p>
        </div>

        <% if @event.address %>
        <div class="notification">
          <h2 class="title">Localização</h2>
          <iframe
            width="100%"
            height="450"
            frameborder="0" style="border:0"
            src="https://www.google.com/maps/embed/v1/place?key=AIzaSyDxzkQbHX7ywePwisa8-g0MlmM1Zfff76M&q=<%= @event.address %>" allowfullscreen>
          </iframe>
        </div>
        <% end %>
      
      </div>
    </div>

    <div class="columns">
      <div class="column">

        <div class="notification">
          <h2 class="title">Comentários</h2>

          <div id="disqus_thread"></div>
          <script>

          /**
          *  RECOMMENDED CONFIGURATION VARIABLES: EDIT AND UNCOMMENT THE SECTION BELOW TO INSERT DYNAMIC VALUES FROM YOUR PLATFORM OR CMS.
          *  LEARN WHY DEFINING THESE VARIABLES IS IMPORTANT: https://disqus.com/admin/universalcode/#configuration-variables*/
          var disqus_config = function () {
          this.page.url = '<%= url_for(:only_path => false) %>';  // Replace PAGE_URL with your page's canonical URL variable
          this.page.identifier = 'event-<%= @event.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
          };
          (function() { // DON'T EDIT BELOW THIS LINE
          var d = document, s = d.createElement('script');
          s.src = '//devents.disqus.com/embed.js';
          s.setAttribute('data-timestamp', +new Date());
          (d.head || d.body).appendChild(s);
          })();
          </script>
          <noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        </div>
      
      </div>
    </div>


  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Devents</title>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.3.1/css/bulma.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <nav class="nav has-shadow">
      <div class="nav-left">
        <a class="nav-item logo" href="<%= root_path %>">
          Devents
        </a>
        <div class="nav-left nav-menu">
          <a class="nav-item is-tab <%= 'is-active' if current_page?(root_path) %>" href="<%= root_path %>">
            Home
          </a>
          <a class="nav-item is-tab" href="https://github.com/lhas/devents" target="_blank">
            Contribuir
          </a>
          <a class="nav-item is-tab" href="<%= contact_path %>">
            Contato
          </a>
          <span class="nav-item">
            <a class="button is-danger" href="<%= new_event_path %>">
              <span class="icon">
                <i class="material-icons">send</i>
              </span>
              <span>Sugerir Evento</span>
            </a>
          </span>
        </div>
      </div>

      <!-- This "nav-toggle" hamburger menu is only visible on mobile -->
      <!-- You need JavaScript to toggle the "is-active" class on "nav-menu" -->
      <span class="nav-toggle">
        <span></span>
        <span></span>
        <span></span>
      </span>

    </nav>

    <%= yield %>

    <footer class="footer">
      <div class="container">
        <div class="content has-text-centered">
          <p>
            <strong>Devents</strong> por <a href="https://github.com/lhas" target="_blank">@lhas</a>. Este projeto é open-source. Sinta-se livre para contribuir!
          </p>
          <p>
            <a class="icon" href="https://github.com/lhas/devents">
              <i class="fa fa-github"></i>
            </a>
          </p>
        </div>
      </div>
    </footer>

  </body>
</html>